// Gallery manifest — single source of truth for the concept gallery.
// This pure-data module drives concepts/gallery/index.js.
// The order of CONCEPTS is the display order in the gallery.

// Consolidated 2026-08-03: 29 → 20 categories. Merges: scanning→systems,
// optics+labwork→lab, weather→nature, ufo→scifi, workshop+clockwork→mech,
// kitchen+office→home, street+money→city, play+sport→games, insects→garden.
export const CATEGORIES = [
  { id: "geometry", title: "Geometry & Pattern" },
  { id: "systems", title: "Systems & Scanning" },
  { id: "bio", title: "Science & Bio" },
  { id: "lab", title: "Lab & Optics" },
  { id: "nature", title: "Nature & Weather" },
  { id: "space", title: "Space & Spatial" },
  { id: "scifi", title: "Sci-Fi & Encounters" },
  { id: "occult", title: "Supernatural & Occult" },
  { id: "arcane", title: "Magic & Arcane" },
  { id: "retro", title: "Retro & Symbolic" },
  { id: "mech", title: "Mechanisms & Tools" },
  { id: "home", title: "Home & Office" },
  { id: "ocean", title: "Ocean & Deep" },
  { id: "city", title: "City & Commerce" },
  { id: "music", title: "Music & Sound" },
  { id: "games", title: "Games & Sport" },
  { id: "garden", title: "Garden & Insects" },
  { id: "birds", title: "Birds & Aviary" },
  { id: "textile", title: "Textiles & Craft" },
  { id: "toys", title: "Toys & Playthings" },
];

export const CONCEPTS = [
  {
    tag: "concept-grid",
    label: "Grid",
    category: "geometry",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-07-23T20:34:33Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-hex",
    label: "Hex",
    category: "geometry",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-lattice",
    label: "Diamond Lattice",
    category: "geometry",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-04-20T08:39:34Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-square-stack",
    label: "Square Stack",
    category: "geometry",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-04-20T08:39:34Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-triangle-mesh",
    label: "Triangle Mesh",
    category: "geometry",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-04-20T08:39:34Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-cube",
    label: "Cube Spin",
    category: "geometry",
    added: "2026-07-22T21:25:08Z",
    updated: "2026-07-22T21:25:08Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-lissajous",
    label: "Lissajous",
    category: "geometry",
    added: "2026-07-23T12:29:20Z",
    updated: "2026-07-23T20:32:04Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-moire",
    label: "Moiré Rings",
    category: "geometry",
    added: "2026-07-23T12:29:20Z",
    updated: "2026-07-23T12:29:20Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-fibonacci",
    label: "Fibonacci Spiral",
    category: "geometry",
    added: "2026-07-23T12:29:20Z",
    updated: "2026-07-23T20:31:49Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-pendulum-wave",
    label: "Pendulum Wave",
    category: "geometry",
    added: "2026-07-23T12:29:20Z",
    updated: "2026-07-23T12:29:20Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-fractal-tree",
    label: "Fractal Tree",
    category: "geometry",
    added: "2026-07-23T12:29:20Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-radar",
    label: "Radar",
    category: "systems",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-04-20T08:39:34Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-eye",
    label: "Eye",
    category: "systems",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-target-lock",
    label: "Target Lock",
    category: "systems",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-07-23T12:00:38Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-sonar",
    label: "Sonar",
    category: "systems",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-04-20T08:39:34Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-compass",
    label: "Compass",
    category: "systems",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-04-20T08:39:34Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-fingerprint",
    label: "Fingerprint Scan",
    category: "systems",
    added: "2026-07-22T21:25:08Z",
    updated: "2026-07-22T21:25:08Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-binary-counter",
    label: "Bin Counter",
    category: "systems",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-07-23T12:06:06Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-noise",
    label: "Digital Noise",
    category: "systems",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-07-23T12:00:38Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-loading-bar",
    label: "Loading Bar",
    category: "systems",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-07-23T12:00:38Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-server-lights",
    label: "Server Rack",
    category: "systems",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-signal",
    label: "Signal",
    category: "systems",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-07-23T12:00:38Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-circuit",
    label: "Circuit",
    category: "systems",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v3",
    badgeCls: "meta-status-refined",
    default: "v3",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
      { v: "v3", badge: "Refined v3", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-ascii",
    label: "ASCII Box",
    category: "systems",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-07-24T07:08:04Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-glitch",
    label: "Glitch Text",
    category: "systems",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-07-23T12:06:06Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-pulse",
    label: "Pulse",
    category: "bio",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-04-20T08:39:34Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-bio",
    label: "Bio-Rhythm",
    category: "bio",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-dna-helix",
    label: "DNA Helix",
    category: "bio",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-04-20T08:39:34Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-atom",
    label: "Atom",
    category: "bio",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-07-23T12:06:06Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-ekg",
    label: "EKG",
    category: "bio",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-07-23T12:06:06Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-molecule",
    label: "Molecule Chain",
    category: "bio",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-cell-cluster",
    label: "Cell Cluster",
    category: "bio",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-neuron",
    label: "Neuron",
    category: "bio",
    added: "2026-07-23T12:54:58Z",
    updated: "2026-07-23T12:54:58Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-petri",
    label: "Petri Dish",
    category: "bio",
    added: "2026-07-23T12:54:58Z",
    updated: "2026-07-23T12:54:58Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-virus",
    label: "Virus",
    category: "bio",
    added: "2026-08-01T12:00:00Z",
    updated: "2026-08-01T12:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-microscope",
    label: "Microscope",
    category: "bio",
    added: "2026-07-23T12:54:58Z",
    updated: "2026-08-01T12:00:00Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-microbes",
    label: "Microbial Field",
    category: "bio",
    added: "2026-08-01T12:00:00Z",
    updated: "2026-08-01T12:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-blood",
    label: "Blood Flow",
    category: "bio",
    added: "2026-07-23T12:54:58Z",
    updated: "2026-07-23T12:54:58Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-rain",
    label: "Rainfall",
    category: "nature",
    added: "2026-07-22T21:25:08Z",
    updated: "2026-07-22T21:25:08Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-lightning",
    label: "Lightning",
    category: "nature",
    added: "2026-07-22T21:25:08Z",
    updated: "2026-07-22T21:25:08Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-aurora",
    label: "Aurora",
    category: "nature",
    added: "2026-07-22T21:25:08Z",
    updated: "2026-07-22T21:25:08Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-ocean-wave",
    label: "Ocean Waves",
    category: "nature",
    added: "2026-07-22T21:25:08Z",
    updated: "2026-07-22T21:25:08Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-ember",
    label: "Ember",
    category: "nature",
    added: "2026-07-22T21:25:08Z",
    updated: "2026-07-22T21:25:08Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-snowfall",
    label: "Snowfall",
    category: "nature",
    added: "2026-07-23T01:07:19Z",
    updated: "2026-07-23T01:07:19Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-tornado",
    label: "Tornado",
    category: "nature",
    added: "2026-07-23T01:07:19Z",
    updated: "2026-07-23T01:07:19Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-firefly",
    label: "Fireflies",
    category: "nature",
    added: "2026-07-23T01:07:19Z",
    updated: "2026-07-23T01:07:19Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-sprout",
    label: "Sprout",
    category: "nature",
    added: "2026-07-23T01:07:19Z",
    updated: "2026-07-23T01:07:19Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-volcano",
    label: "Volcano",
    category: "nature",
    added: "2026-07-23T01:07:19Z",
    updated: "2026-07-23T01:07:19Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-galaxy",
    label: "Galaxy",
    category: "space",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-04-20T08:39:34Z",
    versioned: true,
    badge: "Refined v3",
    badgeCls: "meta-status-refined",
    default: "v3",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
      { v: "v3", badge: "Refined v3", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-constellation",
    label: "Constellation",
    category: "space",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-08-01T12:00:00Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-star-chart",
    label: "Star Chart",
    category: "space",
    added: "2026-08-01T12:00:00Z",
    updated: "2026-08-01T12:00:00Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-wormhole",
    label: "Wormhole",
    category: "space",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-07-23T12:09:19Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-planet-rings",
    label: "Planet Rings",
    category: "space",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-wireframe-globe",
    label: "Wireframe Globe",
    category: "space",
    added: "2026-07-23T20:34:33Z",
    updated: "2026-07-23T20:34:33Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-eclipse",
    label: "Eclipse",
    category: "space",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-04-20T08:39:34Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-moon-phase",
    label: "Moon Phases",
    category: "space",
    added: "2026-07-22T21:25:08Z",
    updated: "2026-07-22T21:25:08Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-comet",
    label: "Comet",
    category: "space",
    added: "2026-07-23T01:22:47Z",
    updated: "2026-07-23T01:22:47Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-satellite",
    label: "Satellite",
    category: "space",
    added: "2026-07-23T01:22:47Z",
    updated: "2026-07-23T01:22:47Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-rocket",
    label: "Rocket Launch",
    category: "space",
    added: "2026-07-23T01:22:47Z",
    updated: "2026-07-23T01:22:47Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-asteroid",
    label: "Asteroid Drift",
    category: "space",
    added: "2026-07-23T01:22:47Z",
    updated: "2026-07-23T01:22:47Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-saucer",
    label: "Flying Saucer",
    category: "scifi",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-abduction",
    label: "Abduction Beam",
    category: "scifi",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-crop-circle",
    label: "Crop Circles",
    category: "scifi",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-alien-signal",
    label: "Alien Signal",
    category: "scifi",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-mothership",
    label: "Mothership",
    category: "scifi",
    added: "2026-08-03T06:30:00Z",
    updated: "2026-08-03T06:30:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-visitor",
    label: "The Visitor",
    category: "scifi",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-dyson",
    label: "Dyson Swarm",
    category: "scifi",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-warp",
    label: "Warp Jump",
    category: "scifi",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-cryopod",
    label: "Cryo Pod",
    category: "scifi",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-hologram",
    label: "Hologram",
    category: "scifi",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-android",
    label: "Android",
    category: "scifi",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-force-field",
    label: "Force Field",
    category: "scifi",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-terraform",
    label: "Terraform",
    category: "scifi",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-ghost",
    label: "Ghost",
    category: "occult",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-ouija",
    label: "Ouija",
    category: "occult",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-spirit-orbs",
    label: "Spirit Orbs",
    category: "occult",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-candle",
    label: "Séance Candle",
    category: "occult",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-poltergeist",
    label: "Poltergeist",
    category: "occult",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-haunted-mirror",
    label: "Haunted Mirror",
    category: "occult",
    added: "2026-07-23T01:27:22Z",
    updated: "2026-07-23T01:27:22Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-wisp",
    label: "Will-o'-Wisp",
    category: "occult",
    added: "2026-07-23T01:27:22Z",
    updated: "2026-07-23T01:27:22Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-raven",
    label: "Raven",
    category: "occult",
    added: "2026-07-23T01:27:22Z",
    updated: "2026-07-23T20:40:42Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-spirit-box",
    label: "Spirit Box",
    category: "occult",
    added: "2026-07-23T01:27:22Z",
    updated: "2026-07-23T01:27:22Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-graveyard",
    label: "Graveyard Mist",
    category: "occult",
    added: "2026-07-23T01:27:22Z",
    updated: "2026-07-23T01:27:22Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-crystal-ball",
    label: "Crystal Ball",
    category: "arcane",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-spellbook",
    label: "Spellbook",
    category: "arcane",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-potion",
    label: "Potion",
    category: "arcane",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-rune-circle",
    label: "Rune Circle",
    category: "arcane",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-wand",
    label: "Wand Cast",
    category: "arcane",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-cauldron",
    label: "Cauldron",
    category: "arcane",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-tarot",
    label: "Tarot Draw",
    category: "arcane",
    added: "2026-07-22T22:19:02Z",
    updated: "2026-07-22T22:19:02Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-pacman",
    label: "Pacman",
    category: "retro",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v3",
    badgeCls: "meta-status-refined",
    default: "v3",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
      { v: "v3", badge: "Refined v3", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-audio-circle",
    label: "Audio Circle",
    category: "retro",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-07-23T12:09:19Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-hourglass",
    label: "Hourglass",
    category: "retro",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-04-20T08:39:34Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-cursor-prompt",
    label: "Cursor Prompt",
    category: "retro",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-04-20T08:39:34Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-joystick",
    label: "Joystick",
    category: "retro",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-tape-reels",
    label: "Tape Reels",
    category: "retro",
    added: "2026-04-20T08:39:34Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-invader",
    label: "Space Invader",
    category: "retro",
    added: "2026-07-22T21:25:08Z",
    updated: "2026-07-22T21:25:08Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-tetris",
    label: "Falling Blocks",
    category: "retro",
    added: "2026-07-23T01:18:42Z",
    updated: "2026-07-23T01:18:42Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-pong",
    label: "Pong Rally",
    category: "retro",
    added: "2026-07-23T01:18:42Z",
    updated: "2026-07-23T01:18:42Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-turntable",
    label: "Turntable",
    category: "retro",
    added: "2026-07-23T01:18:42Z",
    updated: "2026-07-23T01:18:42Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-polaroid",
    label: "Instant Photo",
    category: "retro",
    added: "2026-07-23T01:18:42Z",
    updated: "2026-07-23T01:18:42Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-rotary-dial",
    label: "Rotary Dial",
    category: "retro",
    added: "2026-07-23T01:18:42Z",
    updated: "2026-07-23T01:18:42Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-gears",
    label: "Gears",
    category: "mech",
    added: "2026-07-23T01:14:01Z",
    updated: "2026-07-23T01:14:01Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-pendulum",
    label: "Pendulum",
    category: "mech",
    added: "2026-07-23T01:14:01Z",
    updated: "2026-07-23T01:14:01Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-clock-face",
    label: "Clock Face",
    category: "mech",
    added: "2026-07-23T01:14:01Z",
    updated: "2026-07-23T01:14:01Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-piston",
    label: "Piston",
    category: "mech",
    added: "2026-07-23T01:14:01Z",
    updated: "2026-07-23T01:14:01Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-orrery",
    label: "Orrery",
    category: "mech",
    added: "2026-07-23T01:14:01Z",
    updated: "2026-07-23T01:14:01Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-combo-lock",
    label: "Combo Lock",
    category: "mech",
    added: "2026-07-23T01:14:01Z",
    updated: "2026-07-23T01:14:01Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-toaster",
    label: "Toaster",
    category: "home",
    added: "2026-07-23T12:16:31Z",
    updated: "2026-07-23T12:16:31Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-kettle",
    label: "Kettle",
    category: "home",
    added: "2026-07-23T12:16:31Z",
    updated: "2026-07-23T12:16:31Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-coffee",
    label: "Coffee Cup",
    category: "home",
    added: "2026-07-23T12:16:31Z",
    updated: "2026-07-23T12:16:31Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-microwave",
    label: "Microwave",
    category: "home",
    added: "2026-07-23T12:16:31Z",
    updated: "2026-07-23T12:16:31Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-blender",
    label: "Blender",
    category: "home",
    added: "2026-07-23T12:16:31Z",
    updated: "2026-07-23T12:16:31Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-jellyfish",
    label: "Jellyfish",
    category: "ocean",
    added: "2026-07-23T12:21:00Z",
    updated: "2026-07-23T12:21:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-submarine",
    label: "Submarine",
    category: "ocean",
    added: "2026-07-23T12:21:00Z",
    updated: "2026-07-23T12:21:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-angler",
    label: "Anglerfish",
    category: "ocean",
    added: "2026-07-23T12:21:00Z",
    updated: "2026-07-23T12:21:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-bubble-column",
    label: "Bubble Column",
    category: "ocean",
    added: "2026-07-23T12:21:00Z",
    updated: "2026-07-23T12:21:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-kelp",
    label: "Kelp Forest",
    category: "ocean",
    added: "2026-07-23T12:21:00Z",
    updated: "2026-07-23T12:21:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-traffic-light",
    label: "Traffic Light",
    category: "city",
    added: "2026-07-23T12:25:57Z",
    updated: "2026-07-23T12:25:57Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-crosswalk",
    label: "Crosswalk Signal",
    category: "city",
    added: "2026-07-23T12:25:57Z",
    updated: "2026-07-23T12:25:57Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-train-crossing",
    label: "Train Crossing",
    category: "city",
    added: "2026-07-23T12:25:57Z",
    updated: "2026-07-23T12:25:57Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-balloon",
    label: "Hot Air Balloon",
    category: "city",
    added: "2026-07-23T12:25:57Z",
    updated: "2026-07-23T12:25:57Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-ferris",
    label: "Ferris Wheel",
    category: "city",
    added: "2026-07-23T12:25:57Z",
    updated: "2026-07-23T12:25:57Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-metronome",
    label: "Metronome",
    category: "music",
    added: "2026-07-23T12:33:49Z",
    updated: "2026-07-23T12:33:49Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-piano",
    label: "Piano Keys",
    category: "music",
    added: "2026-07-23T12:33:49Z",
    updated: "2026-07-23T12:33:49Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-tuning-fork",
    label: "Tuning Fork",
    category: "music",
    added: "2026-07-23T12:33:49Z",
    updated: "2026-07-23T12:33:49Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-bell",
    label: "Bell",
    category: "music",
    added: "2026-07-23T12:33:49Z",
    updated: "2026-07-23T12:33:49Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-music-box",
    label: "Music Box",
    category: "music",
    added: "2026-07-23T12:33:49Z",
    updated: "2026-07-23T12:33:49Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-chimes",
    label: "Wind Chimes",
    category: "music",
    added: "2026-07-23T12:33:49Z",
    updated: "2026-07-23T12:33:49Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-level",
    label: "Spirit Level",
    category: "mech",
    added: "2026-07-23T12:41:23Z",
    updated: "2026-07-23T12:41:23Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-wrench",
    label: "Wrench & Bolt",
    category: "mech",
    added: "2026-07-23T12:41:23Z",
    updated: "2026-07-23T12:41:23Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-solder",
    label: "Soldering Iron",
    category: "mech",
    added: "2026-07-23T12:41:23Z",
    updated: "2026-07-23T12:41:23Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-dice",
    label: "Dice Roll",
    category: "games",
    added: "2026-07-23T12:46:18Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-roulette",
    label: "Roulette",
    category: "games",
    added: "2026-07-23T12:46:18Z",
    updated: "2026-07-23T12:46:18Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-pinball",
    label: "Pinball",
    category: "games",
    added: "2026-07-23T12:46:18Z",
    updated: "2026-07-23T12:46:18Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-claw",
    label: "Claw Machine",
    category: "games",
    added: "2026-07-23T12:46:18Z",
    updated: "2026-07-23T12:46:18Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-yoyo",
    label: "Yo-Yo",
    category: "games",
    added: "2026-07-23T12:46:18Z",
    updated: "2026-07-23T12:46:18Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-kite",
    label: "Kite",
    category: "games",
    added: "2026-07-23T12:46:18Z",
    updated: "2026-07-23T12:46:18Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-lighthouse",
    label: "Lighthouse",
    category: "lab",
    added: "2026-07-23T12:50:32Z",
    updated: "2026-07-23T12:50:32Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-prism",
    label: "Prism",
    category: "lab",
    added: "2026-07-23T12:50:32Z",
    updated: "2026-07-23T12:50:32Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-disco",
    label: "Disco Ball",
    category: "lab",
    added: "2026-07-23T12:50:32Z",
    updated: "2026-07-23T20:40:42Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-neon",
    label: "Neon Sign",
    category: "lab",
    added: "2026-07-23T12:50:32Z",
    updated: "2026-07-23T12:50:32Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-flashlight",
    label: "Flashlight",
    category: "lab",
    added: "2026-07-23T12:50:32Z",
    updated: "2026-07-23T12:50:32Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-projector",
    label: "Film Projector",
    category: "lab",
    added: "2026-07-23T12:50:32Z",
    updated: "2026-07-23T12:50:32Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-weathervane",
    label: "Weather Vane",
    category: "nature",
    added: "2026-07-23T12:59:36Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-windsock",
    label: "Windsock",
    category: "nature",
    added: "2026-07-23T12:59:36Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-thermometer",
    label: "Thermometer",
    category: "nature",
    added: "2026-07-23T12:59:36Z",
    updated: "2026-07-23T12:59:36Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-raingauge",
    label: "Rain Gauge",
    category: "nature",
    added: "2026-07-23T12:59:36Z",
    updated: "2026-07-23T12:59:36Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-anemometer",
    label: "Anemometer",
    category: "nature",
    added: "2026-07-23T12:59:36Z",
    updated: "2026-07-23T12:59:36Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-flower",
    label: "Daisy Bloom",
    category: "garden",
    added: "2026-07-23T13:06:11Z",
    updated: "2026-07-23T13:06:11Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-watering-can",
    label: "Watering Can",
    category: "garden",
    added: "2026-07-23T13:06:11Z",
    updated: "2026-07-23T20:40:41Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-bee",
    label: "Bee",
    category: "garden",
    added: "2026-07-23T13:06:11Z",
    updated: "2026-07-23T13:06:11Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-butterfly",
    label: "Butterfly",
    category: "garden",
    added: "2026-07-23T13:06:11Z",
    updated: "2026-07-23T13:06:11Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-ladybug",
    label: "Ladybug",
    category: "garden",
    added: "2026-07-23T13:06:11Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-flytrap",
    label: "Venus Flytrap",
    category: "garden",
    added: "2026-07-23T13:06:11Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-stapler",
    label: "Stapler",
    category: "home",
    added: "2026-07-23T13:10:45Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-sharpener",
    label: "Pencil Sharpener",
    category: "home",
    added: "2026-07-23T13:10:45Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-stamp",
    label: "Rubber Stamp",
    category: "home",
    added: "2026-07-23T13:10:45Z",
    updated: "2026-07-23T13:10:45Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-typewriter",
    label: "Typewriter",
    category: "home",
    added: "2026-07-23T13:10:45Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-deskfan",
    label: "Desk Fan",
    category: "home",
    added: "2026-07-23T13:10:45Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-bunsen",
    label: "Bunsen Burner",
    category: "lab",
    added: "2026-07-23T13:15:34Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-beaker",
    label: "Boiling Beaker",
    category: "lab",
    added: "2026-07-23T13:15:34Z",
    updated: "2026-07-23T13:15:34Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-testtube",
    label: "Test Tube Rack",
    category: "lab",
    added: "2026-07-23T13:15:34Z",
    updated: "2026-07-23T13:15:34Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-distillation",
    label: "Distillation",
    category: "lab",
    added: "2026-07-23T13:15:34Z",
    updated: "2026-07-23T13:15:34Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-centrifuge",
    label: "Centrifuge",
    category: "lab",
    added: "2026-07-23T13:15:34Z",
    updated: "2026-07-23T13:15:34Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-titration",
    label: "Titration",
    category: "lab",
    added: "2026-07-23T13:15:34Z",
    updated: "2026-07-23T13:15:34Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-dartboard",
    label: "Darts",
    category: "games",
    added: "2026-07-23T13:20:26Z",
    updated: "2026-07-23T13:20:26Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-bowling",
    label: "Bowling Strike",
    category: "games",
    added: "2026-07-23T13:20:26Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-golf",
    label: "Golf Putt",
    category: "games",
    added: "2026-07-23T13:20:26Z",
    updated: "2026-07-23T13:20:26Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-billiards",
    label: "Billiards Break",
    category: "games",
    added: "2026-07-23T13:20:26Z",
    updated: "2026-07-23T13:20:26Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-owl",
    label: "Owl",
    category: "birds",
    added: "2026-07-23T13:25:30Z",
    updated: "2026-07-23T13:25:30Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-hummingbird",
    label: "Hummingbird",
    category: "birds",
    added: "2026-07-23T13:25:30Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-woodpecker",
    label: "Woodpecker",
    category: "birds",
    added: "2026-07-23T13:25:30Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-peacock",
    label: "Peacock",
    category: "birds",
    added: "2026-07-23T13:25:30Z",
    updated: "2026-07-23T13:25:30Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-swan",
    label: "Swan",
    category: "birds",
    added: "2026-07-23T13:25:30Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-hatchling",
    label: "Hatchling",
    category: "birds",
    added: "2026-07-23T13:25:30Z",
    updated: "2026-07-23T13:25:30Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-sewing-machine",
    label: "Sewing Machine",
    category: "textile",
    added: "2026-07-23T13:30:25Z",
    updated: "2026-07-23T13:30:25Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-knitting",
    label: "Knitting",
    category: "textile",
    added: "2026-07-23T13:30:25Z",
    updated: "2026-07-23T13:30:25Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-spinning-wheel",
    label: "Spinning Wheel",
    category: "textile",
    added: "2026-07-23T13:30:25Z",
    updated: "2026-07-23T13:30:25Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-loom",
    label: "Loom",
    category: "textile",
    added: "2026-07-23T13:30:25Z",
    updated: "2026-07-23T13:30:25Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-zipper",
    label: "Zipper",
    category: "textile",
    added: "2026-07-23T13:30:25Z",
    updated: "2026-07-23T13:30:25Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-scissors",
    label: "Scissors",
    category: "textile",
    added: "2026-07-23T13:30:25Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-cash-register",
    label: "Cash Register",
    category: "city",
    added: "2026-07-23T13:35:32Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-coinflip",
    label: "Coin Flip",
    category: "city",
    added: "2026-07-23T13:35:32Z",
    updated: "2026-08-03T05:11:30Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-vending",
    label: "Vending Machine",
    category: "city",
    added: "2026-07-23T13:35:32Z",
    updated: "2026-07-23T13:35:32Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-atm",
    label: "Cash Machine",
    category: "city",
    added: "2026-07-23T13:35:32Z",
    updated: "2026-07-23T13:35:32Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-balance-scale",
    label: "Balance Scale",
    category: "city",
    added: "2026-07-23T13:35:32Z",
    updated: "2026-07-23T13:35:32Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-piggybank",
    label: "Piggy Bank",
    category: "city",
    added: "2026-07-23T13:35:32Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-spinning-top",
    label: "Spinning Top",
    category: "toys",
    added: "2026-07-23T13:40:26Z",
    updated: "2026-07-23T13:40:26Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-jackbox",
    label: "Jack-in-the-Box",
    category: "toys",
    added: "2026-07-23T13:40:26Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-rubber-duck",
    label: "Rubber Duck",
    category: "toys",
    added: "2026-07-23T13:40:26Z",
    updated: "2026-07-23T13:40:26Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-slinky",
    label: "Slinky",
    category: "toys",
    added: "2026-07-23T13:40:26Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-blocks",
    label: "Building Blocks",
    category: "toys",
    added: "2026-07-23T13:40:26Z",
    updated: "2026-07-23T13:40:26Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-windup-robot",
    label: "Wind-up Robot",
    category: "toys",
    added: "2026-07-23T13:40:26Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-spider",
    label: "Spider",
    category: "garden",
    added: "2026-07-23T13:45:23Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-ant",
    label: "Ant",
    category: "garden",
    added: "2026-07-23T13:45:23Z",
    updated: "2026-07-23T13:45:23Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-dragonfly",
    label: "Dragonfly",
    category: "garden",
    added: "2026-07-23T13:45:23Z",
    updated: "2026-07-23T13:45:23Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-grasshopper",
    label: "Grasshopper",
    category: "garden",
    added: "2026-07-23T13:45:23Z",
    updated: "2026-07-23T13:45:23Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-caterpillar",
    label: "Caterpillar",
    category: "garden",
    added: "2026-07-23T13:45:23Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-mantis",
    label: "Praying Mantis",
    category: "garden",
    added: "2026-07-23T13:45:23Z",
    updated: "2026-08-03T05:20:39Z",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "New v1", badgeCls: "meta-status-new" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
];
