// Gallery manifest — single source of truth for the concept gallery.
// This pure-data module drives concepts/gallery/index.js.
// The order of CONCEPTS is the display order in the gallery.

export const CATEGORIES = [
  { id: "geometry", title: "Geometry & Pattern" },
  { id: "scanning", title: "Scanning & Targeting" },
  { id: "systems", title: "Systems & Diagnostics" },
  { id: "bio", title: "Science & Bio" },
  { id: "space", title: "Space & Spatial" },
  { id: "retro", title: "Retro & Symbolic" },
];

export const CONCEPTS = [
  {
    tag: "concept-grid",
    label: "Grid",
    category: "geometry",
    versioned: false,
    badge: "Original v1",
    badgeCls: "meta-status-original",
    default: null,
    versions: [],
  },
  {
    tag: "concept-hex",
    label: "Hex",
    category: "geometry",
    versioned: false,
    badge: "Original v1",
    badgeCls: "meta-status-original",
    default: null,
    versions: [],
  },
  {
    tag: "concept-lattice",
    label: "Diamond Lattice",
    category: "geometry",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-square-stack",
    label: "Square Stack",
    category: "geometry",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-triangle-mesh",
    label: "Triangle Mesh",
    category: "geometry",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-weave-grid",
    label: "Weave Grid",
    category: "geometry",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-radar",
    label: "Radar",
    category: "scanning",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-eye",
    label: "Eye",
    category: "scanning",
    versioned: false,
    badge: "Original v1",
    badgeCls: "meta-status-original",
    default: null,
    versions: [],
  },
  {
    tag: "concept-target-lock",
    label: "Target Lock",
    category: "scanning",
    versioned: false,
    badge: "Original v1",
    badgeCls: "meta-status-original",
    default: null,
    versions: [],
  },
  {
    tag: "concept-sonar",
    label: "Sonar",
    category: "scanning",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-laser-scan",
    label: "Laser Scan",
    category: "scanning",
    versioned: false,
    badge: "Original v1",
    badgeCls: "meta-status-original",
    default: null,
    versions: [],
  },
  {
    tag: "concept-compass",
    label: "Compass",
    category: "scanning",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-binary-counter",
    label: "Bin Counter",
    category: "systems",
    versioned: false,
    badge: "Original v1",
    badgeCls: "meta-status-original",
    default: null,
    versions: [],
  },
  {
    tag: "concept-noise",
    label: "Digital Noise",
    category: "systems",
    versioned: false,
    badge: "Original v1",
    badgeCls: "meta-status-original",
    default: null,
    versions: [],
  },
  {
    tag: "concept-loading-bar",
    label: "Loading Bar",
    category: "systems",
    versioned: false,
    badge: "Original v1",
    badgeCls: "meta-status-original",
    default: null,
    versions: [],
  },
  {
    tag: "concept-server-lights",
    label: "Server Rack",
    category: "systems",
    versioned: false,
    badge: "Original v1",
    badgeCls: "meta-status-original",
    default: null,
    versions: [],
  },
  {
    tag: "concept-signal",
    label: "Signal",
    category: "systems",
    versioned: false,
    badge: "Original v1",
    badgeCls: "meta-status-original",
    default: null,
    versions: [],
  },
  {
    tag: "concept-circuit",
    label: "Circuit",
    category: "systems",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-ascii",
    label: "ASCII Box",
    category: "systems",
    versioned: false,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: null,
    versions: [],
  },
  {
    tag: "concept-glitch",
    label: "Glitch Text",
    category: "systems",
    versioned: false,
    badge: "Original v1",
    badgeCls: "meta-status-original",
    default: null,
    versions: [],
  },
  {
    tag: "concept-pulse",
    label: "Pulse",
    category: "bio",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-bio",
    label: "Bio-Rhythm",
    category: "bio",
    versioned: false,
    badge: "Original v1",
    badgeCls: "meta-status-original",
    default: null,
    versions: [],
  },
  {
    tag: "concept-dna-helix",
    label: "DNA Helix",
    category: "bio",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-atom",
    label: "Atom",
    category: "bio",
    versioned: false,
    badge: "Original v1",
    badgeCls: "meta-status-original",
    default: null,
    versions: [],
  },
  {
    tag: "concept-ekg",
    label: "EKG",
    category: "bio",
    versioned: false,
    badge: "Original v1",
    badgeCls: "meta-status-original",
    default: null,
    versions: [],
  },
  {
    tag: "concept-molecule",
    label: "Molecule Chain",
    category: "bio",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-cell-cluster",
    label: "Cell Cluster",
    category: "bio",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-galaxy",
    label: "Galaxy",
    category: "space",
    versioned: true,
    badge: "Refined v3",
    badgeCls: "meta-status-refined",
    default: "v3",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
      { v: "v3", badge: "Refined v3", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-constellation",
    label: "Constellation",
    category: "space",
    versioned: true,
    badge: "Refined v4",
    badgeCls: "meta-status-refined",
    default: "v4",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
      { v: "v3", badge: "Refined v3", badgeCls: "meta-status-refined" },
      { v: "v4", badge: "Refined v4", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-wormhole",
    label: "Wormhole",
    category: "space",
    versioned: false,
    badge: "Original v1",
    badgeCls: "meta-status-original",
    default: null,
    versions: [],
  },
  {
    tag: "concept-portal",
    label: "Portal",
    category: "space",
    versioned: false,
    badge: "Original v1",
    badgeCls: "meta-status-original",
    default: null,
    versions: [],
  },
  {
    tag: "concept-planet-rings",
    label: "Planet Rings",
    category: "space",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-eclipse",
    label: "Eclipse",
    category: "space",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-pacman",
    label: "Pacman",
    category: "retro",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-audio-circle",
    label: "Audio Circle",
    category: "retro",
    versioned: false,
    badge: "Original v1",
    badgeCls: "meta-status-original",
    default: null,
    versions: [],
  },
  {
    tag: "concept-hourglass",
    label: "Hourglass",
    category: "retro",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-cursor-prompt",
    label: "Cursor Prompt",
    category: "retro",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-joystick",
    label: "Joystick",
    category: "retro",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-tape-reels",
    label: "Tape Reels",
    category: "retro",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
];
