// Gallery manifest — single source of truth for the concept gallery.
// This pure-data module drives concepts/gallery/index.js.
// The order of CONCEPTS is the display order in the gallery.

export const CATEGORIES = [
  { id: "geometry", title: "Geometry & Pattern" },
  { id: "scanning", title: "Scanning & Targeting" },
  { id: "systems", title: "Systems & Diagnostics" },
  { id: "bio", title: "Science & Bio" },
  { id: "nature", title: "Nature & Elements" },
  { id: "space", title: "Space & Spatial" },
  { id: "ufo", title: "UFOs & Encounters" },
  { id: "scifi", title: "High Sci-Fi" },
  { id: "occult", title: "Supernatural & Occult" },
  { id: "arcane", title: "Magic & Arcane" },
  { id: "retro", title: "Retro & Symbolic" },
  { id: "clockwork", title: "Clockwork & Mechanisms" },
  { id: "kitchen", title: "Kitchen & Appliance" },
  { id: "ocean", title: "Ocean & Deep" },
  { id: "street", title: "Street & Transit" },
  { id: "music", title: "Music & Sound" },
  { id: "workshop", title: "Workshop & Tools" },
  { id: "play", title: "Games & Play" },
  { id: "optics", title: "Light & Optics" },
  { id: "weather", title: "Weather Station" },
  { id: "garden", title: "Garden & Bloom" },
];

export const CONCEPTS = [
  {
    tag: "concept-grid",
    label: "Grid",
    category: "geometry",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-hex",
    label: "Hex",
    category: "geometry",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-lattice",
    label: "Diamond Lattice",
    category: "geometry",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-square-stack",
    label: "Square Stack",
    category: "geometry",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-triangle-mesh",
    label: "Triangle Mesh",
    category: "geometry",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-weave-grid",
    label: "Weave Grid",
    category: "geometry",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-cube",
    label: "Cube Spin",
    category: "geometry",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-lissajous",
    label: "Lissajous",
    category: "geometry",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-moire",
    label: "Moiré Rings",
    category: "geometry",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-fibonacci",
    label: "Fibonacci Spiral",
    category: "geometry",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-pendulum-wave",
    label: "Pendulum Wave",
    category: "geometry",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-fractal-tree",
    label: "Fractal Tree",
    category: "geometry",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-radar",
    label: "Radar",
    category: "scanning",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-eye",
    label: "Eye",
    category: "scanning",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-target-lock",
    label: "Target Lock",
    category: "scanning",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-sonar",
    label: "Sonar",
    category: "scanning",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-laser-scan",
    label: "Laser Scan",
    category: "scanning",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-compass",
    label: "Compass",
    category: "scanning",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-fingerprint",
    label: "Fingerprint Scan",
    category: "scanning",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-binary-counter",
    label: "Bin Counter",
    category: "systems",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-noise",
    label: "Digital Noise",
    category: "systems",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-loading-bar",
    label: "Loading Bar",
    category: "systems",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-server-lights",
    label: "Server Rack",
    category: "systems",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-signal",
    label: "Signal",
    category: "systems",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-circuit",
    label: "Circuit",
    category: "systems",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-ascii",
    label: "ASCII Box",
    category: "systems",
    versioned: false,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: null,
    versions: [],
  },
  {
    tag: "concept-glitch",
    label: "Glitch Text",
    category: "systems",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-pulse",
    label: "Pulse",
    category: "bio",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-bio",
    label: "Bio-Rhythm",
    category: "bio",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-dna-helix",
    label: "DNA Helix",
    category: "bio",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-atom",
    label: "Atom",
    category: "bio",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-ekg",
    label: "EKG",
    category: "bio",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-molecule",
    label: "Molecule Chain",
    category: "bio",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-cell-cluster",
    label: "Cell Cluster",
    category: "bio",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-neuron",
    label: "Neuron",
    category: "bio",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-lungs",
    label: "Lungs",
    category: "bio",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-petri",
    label: "Petri Dish",
    category: "bio",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-microscope",
    label: "Microscope",
    category: "bio",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-blood",
    label: "Blood Flow",
    category: "bio",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-rain",
    label: "Rainfall",
    category: "nature",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-lightning",
    label: "Lightning",
    category: "nature",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-aurora",
    label: "Aurora",
    category: "nature",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-ocean-wave",
    label: "Ocean Waves",
    category: "nature",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-ember",
    label: "Ember",
    category: "nature",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-snowfall",
    label: "Snowfall",
    category: "nature",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-tornado",
    label: "Tornado",
    category: "nature",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-firefly",
    label: "Fireflies",
    category: "nature",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-sprout",
    label: "Sprout",
    category: "nature",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-volcano",
    label: "Volcano",
    category: "nature",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-galaxy",
    label: "Galaxy",
    category: "space",
    versioned: true,
    badge: "Refined v3",
    badgeCls: "meta-status-refined",
    default: "v3",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
      { v: "v3", badge: "Refined v3", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-constellation",
    label: "Constellation",
    category: "space",
    versioned: true,
    badge: "Refined v4",
    badgeCls: "meta-status-refined",
    default: "v4",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
      { v: "v3", badge: "Refined v3", badgeCls: "meta-status-refined" },
      { v: "v4", badge: "Refined v4", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-wormhole",
    label: "Wormhole",
    category: "space",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-portal",
    label: "Portal",
    category: "space",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-planet-rings",
    label: "Planet Rings",
    category: "space",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-eclipse",
    label: "Eclipse",
    category: "space",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-moon-phase",
    label: "Moon Phases",
    category: "space",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-comet",
    label: "Comet",
    category: "space",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-satellite",
    label: "Satellite",
    category: "space",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-rocket",
    label: "Rocket Launch",
    category: "space",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-asteroid",
    label: "Asteroid Drift",
    category: "space",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-saucer",
    label: "Flying Saucer",
    category: "ufo",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-abduction",
    label: "Abduction Beam",
    category: "ufo",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-crop-circle",
    label: "Crop Circles",
    category: "ufo",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-alien-signal",
    label: "Alien Signal",
    category: "ufo",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-mothership",
    label: "Mothership",
    category: "ufo",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-visitor",
    label: "The Visitor",
    category: "ufo",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-dyson",
    label: "Dyson Swarm",
    category: "scifi",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-warp",
    label: "Warp Jump",
    category: "scifi",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-cryopod",
    label: "Cryo Pod",
    category: "scifi",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-hologram",
    label: "Hologram",
    category: "scifi",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-android",
    label: "Android",
    category: "scifi",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-force-field",
    label: "Force Field",
    category: "scifi",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-terraform",
    label: "Terraform",
    category: "scifi",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-ghost",
    label: "Ghost",
    category: "occult",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-ouija",
    label: "Ouija",
    category: "occult",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-spirit-orbs",
    label: "Spirit Orbs",
    category: "occult",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-candle",
    label: "Séance Candle",
    category: "occult",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-skull",
    label: "Skull",
    category: "occult",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-poltergeist",
    label: "Poltergeist",
    category: "occult",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-haunted-mirror",
    label: "Haunted Mirror",
    category: "occult",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-wisp",
    label: "Will-o'-Wisp",
    category: "occult",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-raven",
    label: "Raven",
    category: "occult",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-spirit-box",
    label: "Spirit Box",
    category: "occult",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-graveyard",
    label: "Graveyard Mist",
    category: "occult",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-crystal-ball",
    label: "Crystal Ball",
    category: "arcane",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-spellbook",
    label: "Spellbook",
    category: "arcane",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-potion",
    label: "Potion",
    category: "arcane",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-rune-circle",
    label: "Rune Circle",
    category: "arcane",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-wand",
    label: "Wand Cast",
    category: "arcane",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-cauldron",
    label: "Cauldron",
    category: "arcane",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-tarot",
    label: "Tarot Draw",
    category: "arcane",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-pacman",
    label: "Pacman",
    category: "retro",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-audio-circle",
    label: "Audio Circle",
    category: "retro",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-hourglass",
    label: "Hourglass",
    category: "retro",
    versioned: true,
    badge: "Refined v2",
    badgeCls: "meta-status-refined",
    default: "v2",
    versions: [
      { v: "v1", badge: "Original v1", badgeCls: "meta-status-original" },
      { v: "v2", badge: "Refined v2", badgeCls: "meta-status-refined" },
    ],
  },
  {
    tag: "concept-cursor-prompt",
    label: "Cursor Prompt",
    category: "retro",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-joystick",
    label: "Joystick",
    category: "retro",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-tape-reels",
    label: "Tape Reels",
    category: "retro",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-invader",
    label: "Space Invader",
    category: "retro",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-tetris",
    label: "Falling Blocks",
    category: "retro",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-pong",
    label: "Pong Rally",
    category: "retro",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-turntable",
    label: "Turntable",
    category: "retro",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-polaroid",
    label: "Instant Photo",
    category: "retro",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-rotary-dial",
    label: "Rotary Dial",
    category: "retro",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-gears",
    label: "Gears",
    category: "clockwork",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-pendulum",
    label: "Pendulum",
    category: "clockwork",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-clock-face",
    label: "Clock Face",
    category: "clockwork",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-piston",
    label: "Piston",
    category: "clockwork",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-orrery",
    label: "Orrery",
    category: "clockwork",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-combo-lock",
    label: "Combo Lock",
    category: "clockwork",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-toaster",
    label: "Toaster",
    category: "kitchen",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-kettle",
    label: "Kettle",
    category: "kitchen",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-coffee",
    label: "Coffee Cup",
    category: "kitchen",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-popcorn",
    label: "Popcorn",
    category: "kitchen",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-microwave",
    label: "Microwave",
    category: "kitchen",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-blender",
    label: "Blender",
    category: "kitchen",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-jellyfish",
    label: "Jellyfish",
    category: "ocean",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-submarine",
    label: "Submarine",
    category: "ocean",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-angler",
    label: "Anglerfish",
    category: "ocean",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-bubble-column",
    label: "Bubble Column",
    category: "ocean",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-kelp",
    label: "Kelp Forest",
    category: "ocean",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-depth-gauge",
    label: "Depth Gauge",
    category: "ocean",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-traffic-light",
    label: "Traffic Light",
    category: "street",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-crosswalk",
    label: "Crosswalk Signal",
    category: "street",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-wipers",
    label: "Windshield Wipers",
    category: "street",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-train-crossing",
    label: "Train Crossing",
    category: "street",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-balloon",
    label: "Hot Air Balloon",
    category: "street",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-ferris",
    label: "Ferris Wheel",
    category: "street",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-metronome",
    label: "Metronome",
    category: "music",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-piano",
    label: "Piano Keys",
    category: "music",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-tuning-fork",
    label: "Tuning Fork",
    category: "music",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-bell",
    label: "Bell",
    category: "music",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-music-box",
    label: "Music Box",
    category: "music",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-chimes",
    label: "Wind Chimes",
    category: "music",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-hammer",
    label: "Hammer & Nail",
    category: "workshop",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-saw",
    label: "Handsaw",
    category: "workshop",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-drill",
    label: "Power Drill",
    category: "workshop",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-level",
    label: "Spirit Level",
    category: "workshop",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-wrench",
    label: "Wrench & Bolt",
    category: "workshop",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-solder",
    label: "Soldering Iron",
    category: "workshop",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-dice",
    label: "Dice Roll",
    category: "play",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-roulette",
    label: "Roulette",
    category: "play",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-pinball",
    label: "Pinball",
    category: "play",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-claw",
    label: "Claw Machine",
    category: "play",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-yoyo",
    label: "Yo-Yo",
    category: "play",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-kite",
    label: "Kite",
    category: "play",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-lighthouse",
    label: "Lighthouse",
    category: "optics",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-prism",
    label: "Prism",
    category: "optics",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-disco",
    label: "Disco Ball",
    category: "optics",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-neon",
    label: "Neon Sign",
    category: "optics",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-flashlight",
    label: "Flashlight",
    category: "optics",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-projector",
    label: "Film Projector",
    category: "optics",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-barometer",
    label: "Barometer",
    category: "weather",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-weathervane",
    label: "Weather Vane",
    category: "weather",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-windsock",
    label: "Windsock",
    category: "weather",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-thermometer",
    label: "Thermometer",
    category: "weather",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-raingauge",
    label: "Rain Gauge",
    category: "weather",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-anemometer",
    label: "Anemometer",
    category: "weather",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-flower",
    label: "Daisy Bloom",
    category: "garden",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-watering-can",
    label: "Watering Can",
    category: "garden",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-bee",
    label: "Bee",
    category: "garden",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-butterfly",
    label: "Butterfly",
    category: "garden",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-ladybug",
    label: "Ladybug",
    category: "garden",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "concept-flytrap",
    label: "Venus Flytrap",
    category: "garden",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
];
