import { expansionEntries } from "./expansion-entry.js";

const added = "2026-09-07T09:35:00Z";
export const CONCEPTS = expansionEntries("computing", "algorithms-data-structures", [
  {
    id: "binary-search", label: "Binary Search", aliases: ["interval halving"], added,
    definition: "Binary search locates a key in sorted data by repeatedly discarding the half excluded by a midpoint comparison.",
    motionThesis: "A midpoint probe compares increasing bars to a target height as brackets contract to the matching key.",
    distinction: "Search bounds contract while the ordered data stays in place.",
    facets: ["algorithms", "search", "sorted data"], cycleSeconds: 7,
    references: ["https://algs4.cs.princeton.edu/11model/"],
  },
  {
    id: "merge-sort", label: "Merge Sort", aliases: ["mergesort"], added,
    definition: "Merge sort orders data by merging sorted subsequences produced through recursive division or successive passes.",
    motionThesis: "The smaller of two ordered input heads repeatedly moves into the next output slot in a merge-sort pass.",
    distinction: "Two source fronts feed a separate ordered destination; keys never swap around a pivot.",
    facets: ["algorithms", "sorting", "divide and conquer"], cycleSeconds: 10,
    references: ["https://algs4.cs.princeton.edu/22mergesort/"],
  },
  {
    id: "quicksort-partition", label: "Quicksort Partition", aliases: ["Lomuto partition"], added,
    definition: "A quicksort partition places a pivot between values smaller and larger than it before recursive sorting.",
    motionThesis: "A scan swaps qualifying keys into the smaller-value region, then exchanges the pivot into the partition boundary.",
    distinction: "One explicit partition of a single array rather than a claim to show the entire recursive sort.",
    facets: ["algorithms", "sorting", "divide and conquer"], cycleSeconds: 9,
    references: ["https://algs4.cs.princeton.edu/23quicksort/"],
  },
  {
    id: "breadth-first-search", label: "Breadth-First Search", aliases: ["BFS"], added,
    definition: "Breadth-first search uses a first-in-first-out frontier to discover vertices in increasing unweighted distance from a source.",
    motionThesis: "A queue admits newly discovered neighbors at its tail and removes the front vertex while the discovery tree grows by distance layer.",
    distinction: "A visible FIFO frontier and duplicate-discovery skip distinguish traversal from a decorative radial pulse.",
    facets: ["algorithms", "graphs", "search"], cycleSeconds: 9,
    references: ["https://algs4.cs.princeton.edu/41graph/"],
  },
  {
    id: "dijkstra-shortest-path", label: "Dijkstra Shortest Path", aliases: ["Dijkstra's algorithm"], added,
    definition: "Dijkstra's algorithm finds shortest paths with nonnegative edge weights by settling the smallest tentative distance and relaxing outgoing edges.",
    motionThesis: "Tentative distance bars shrink when a cheaper route is found, and predecessor links change before each minimum-distance vertex is settled.",
    distinction: "Weighted relaxation and revisable predecessor links rather than unweighted discovery layers.",
    facets: ["algorithms", "graphs", "routing"], cycleSeconds: 10,
    references: ["https://algs4.cs.princeton.edu/44sp/"],
  },
  {
    id: "kruskal-spanning-tree", label: "Kruskal Spanning Tree", aliases: ["minimum spanning tree", "MST"], added,
    definition: "Kruskal's algorithm builds a minimum spanning tree by accepting the lightest available edges that join different components.",
    motionThesis: "A sorted edge tray offers edges in increasing weight, rejects a triangle-closing edge, and completes the connecting tree.",
    distinction: "Greedy edge selection with cycle rejection, rather than shortest paths from a source.",
    facets: ["algorithms", "graphs", "greedy methods"], cycleSeconds: 9,
    references: ["https://algs4.cs.princeton.edu/43mst/"],
  },
  {
    id: "union-find", label: "Union-Find", aliases: ["disjoint-set union", "DSU", "path compression"], added,
    definition: "Union-find represents disjoint sets using roots, with path compression shortening parent chains during find operations.",
    motionThesis: "A find traverses a parent chain and redirects its links to the root, then a union joins two roots and a second find flattens the remaining chain.",
    distinction: "Internal parent pointers change while set membership is preserved during compression.",
    facets: ["algorithms", "data structures", "disjoint sets"], cycleSeconds: 9,
    references: ["https://algs4.cs.princeton.edu/15uf/"],
  },
  {
    id: "binary-heap", label: "Binary Heap", aliases: ["max-heap", "priority queue", "swim and sink"], added,
    definition: "A binary max-heap stores a complete binary tree whose parent keys are at least as large as their children.",
    motionThesis: "A new maximum swims through parent exchanges to the root, then removal replaces it with the last key and sinks that key to restore heap order.",
    distinction: "Local priority exchanges preserve a complete tree rather than rebalancing a search tree.",
    facets: ["algorithms", "data structures", "priority queue"], cycleSeconds: 9,
    references: ["https://algs4.cs.princeton.edu/24pq/"],
  },
  {
    id: "radix-sort", label: "Radix Sort", aliases: ["LSD radix sort", "least-significant-digit sort"], added: "2026-09-07T09:48:37Z",
    definition: "Least-significant-digit radix sort orders keys through stable digit-based passes from the least to the most significant position.",
    motionThesis: "Four decimal keys enter units buckets in arrival order, return as a stable run, and repeat for the tens digit to finish sorted.",
    distinction: "Stable distribution by one digit at a time rather than pairwise value comparisons.",
    facets: ["algorithms", "sorting", "stable distribution"], cycleSeconds: 10,
    references: ["https://algs4.cs.princeton.edu/51radix/LSD.java.html"],
  },
  {
    id: "avl-tree-rotation", label: "AVL Tree Rotation", aliases: ["AVL rebalancing", "right rotation"], added: "2026-09-07T09:48:37Z",
    definition: "An AVL tree rotation restores subtree-height balance while preserving binary-search key order.",
    motionThesis: "A left-heavy tree rotates its left child into the root and transfers the middle subtree to the former root while the inorder sequence remains fixed.",
    distinction: "Nodes and parent links move structurally; keys are not exchanged in a fixed heap shape.",
    facets: ["algorithms", "data structures", "balanced search trees"], cycleSeconds: 8,
    references: ["https://xlinux.nist.gov/dads/HTML/avltree.html"],
  },
  {
    id: "linear-probing-hash-table", label: "Linear-Probing Hash Table", aliases: ["linear probing", "open addressing"], added: "2026-09-07T09:48:37Z",
    definition: "Linear probing resolves a hash collision by examining consecutive slots, wrapping around the table until it finds a matching key or an empty slot.",
    motionThesis: "Key 22 hashes to slot four in a six-slot table, encounters keys 10 and 16, wraps from slot five to zero, and enters the empty slot.",
    distinction: "Explicit collision handling and cyclic array probing rather than a generic storage animation.",
    facets: ["algorithms", "data structures", "hashing"], cycleSeconds: 8,
    references: ["https://algs4.cs.princeton.edu/34hash/"],
  },
  {
    id: "prefix-trie", label: "Prefix Trie", aliases: ["trie", "prefix tree"], added: "2026-09-07T09:48:37Z",
    definition: "A trie stores keys along symbol paths, sharing common prefixes and marking complete keys separately.",
    motionThesis: "Inserting CAT and CAR reuses the C–A prefix before branching at their final characters, while DOG builds a separate path.",
    distinction: "Symbol-by-symbol prefix sharing with terminal markers rather than ordered numeric tree comparisons.",
    facets: ["algorithms", "data structures", "strings"], cycleSeconds: 9,
    references: ["https://algs4.cs.princeton.edu/52trie/"],
  },
  {
    id: "topological-sort", label: "Topological Sort", aliases: ["Kahn's algorithm", "dependency ordering"], added: "2026-09-07T09:48:37Z",
    definition: "A topological ordering places each vertex of a directed acyclic graph before all of its outgoing neighbors.",
    motionThesis: "Removing ready vertices releases prerequisite pins, and a vertex enters the output only after its final incoming constraint disappears.",
    distinction: "Dependency release and zero-indegree readiness rather than shortest-distance graph discovery.",
    facets: ["algorithms", "graphs", "scheduling"], cycleSeconds: 10,
    references: ["https://algs4.cs.princeton.edu/42digraph/TopologicalX.java.html"],
  },
  {
    id: "augmenting-path-max-flow", updated: "2026-09-07T16:07:46Z", label: "Augmenting-Path Max Flow", aliases: ["Ford–Fulkerson method", "residual network"], added: "2026-09-07T09:48:37Z",
    definition: "An augmenting-path method increases source-to-sink flow through residual capacity, including reverse edges that cancel earlier assignments.",
    motionThesis: "A first unit crosses a middle edge, then a reverse residual step cancels that allocation and opens two disjoint unit-capacity routes to the sink.",
    distinction: "Flow conservation, capacity use, and explicit cancellation rather than a routing highlight.",
    facets: ["algorithms", "graphs", "network flow"], cycleSeconds: 10,
    references: ["https://algs4.cs.princeton.edu/64maxflow/", "https://algs4.cs.princeton.edu/64maxflow/FlowEdge.java.html"],
  },
  {
    id: "a-star-search", label: "A* Search", aliases: ["A-star", "heuristic best-first search"], added: "2026-09-07T09:48:37Z",
    definition: "A* expands the frontier state with minimum estimated total cost, combining accumulated path cost with a heuristic estimate to the goal.",
    motionThesis: "A grid frontier compares accumulated and Manhattan-estimated costs around a barrier before reconstructing the route when the goal is selected.",
    distinction: "An explicit goal heuristic and spatial obstacle search rather than Dijkstra's weighted-network distance revisions.",
    facets: ["algorithms", "search", "pathfinding"], cycleSeconds: 12,
    references: ["https://artint.info/3e/html/ArtInt3e.Ch3.S6.html"],
  },
  {
    id: "backtracking-maze", label: "Backtracking Maze", aliases: ["recursive backtracking", "maze solving"], added: "2026-09-07T09:48:37Z",
    definition: "Backtracking explores candidate solutions and retracts unsuccessful choices to continue from an earlier branch.",
    motionThesis: "A route enters two walled dead ends, retracts along its own corridor, and keeps the successful path to the exit.",
    distinction: "Physical corridor constraints and visible undoing of a route, with graph-stack traversal reserved for depth-first search.",
    facets: ["algorithms", "search", "backtracking"], cycleSeconds: 11,
    references: ["https://algs4.cs.princeton.edu/41graph/Maze.java.html"],
  },
  {
    id: "depth-first-search", label: "Depth-First Search", aliases: ["DFS", "recursive graph traversal"], added: "2026-09-07T10:00:00Z",
    definition: "Depth-first search recursively explores unvisited neighbors before returning to the preceding vertex.",
    motionThesis: "Call frames push and pop beside a graph while discovery edges remain and completed vertices enter a finish-order strip.",
    distinction: "An explicit recursion stack and completion order rather than retracting a route through physical maze corridors.",
    facets: ["algorithms", "graphs", "recursion"], cycleSeconds: 11,
    references: ["https://algs4.cs.princeton.edu/41graph/"],
  },
  {
    id: "knapsack-dynamic-programming", label: "Knapsack Dynamic Programming", aliases: ["0–1 knapsack", "capacity dynamic programming"], added: "2026-09-07T10:00:00Z",
    definition: "The 0–1 knapsack problem maximizes selected item value within a weight capacity, using each item at most once.",
    motionThesis: "A capacity table compares inclusion with exclusion using previous-row states, then traces back two items that exactly fill capacity five.",
    distinction: "A discrete include-or-exclude recurrence with reduced-capacity dependencies.",
    facets: ["algorithms", "dynamic programming", "optimization"], cycleSeconds: 11,
    references: ["https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/3484e876d81aba07911a1109f5b5e81e_MIT6_006F11_lec21.pdf"],
  },
  {
    id: "edit-distance", label: "Edit Distance", aliases: ["Levenshtein distance", "string edit distance"], added: "2026-09-07T10:00:00Z",
    definition: "Levenshtein distance is the minimum number of single-character insertions, deletions, and substitutions between two strings.",
    motionThesis: "Prefix-pair costs fill a table before a two-edit traceback changes CAT to CUT and then CUTS.",
    distinction: "Character-operation costs and prefix alignment rather than item capacity selection.",
    facets: ["algorithms", "dynamic programming", "strings"], cycleSeconds: 10,
    references: ["https://xlinux.nist.gov/dads/HTML/Levenshtein.html"],
  },
  {
    id: "finite-state-automaton", label: "Finite-State Automaton", aliases: ["DFA", "deterministic finite automaton"], added: "2026-09-07T10:00:00Z",
    definition: "A deterministic finite automaton consumes symbols through finite state transitions and accepts according to its state when input ends.",
    motionThesis: "Ones toggle even and odd parity states while zeros take self-loops, accepting an input with an even number of ones.",
    distinction: "Two states alone retain parity, with no growing counter or stack.",
    facets: ["algorithms", "formal languages", "finite memory"], cycleSeconds: 8,
    references: ["https://ocw.mit.edu/courses/18-404j-theory-of-computation-fall-2020/b4d9bf1573dccea21bee82cfba4224d4_MIT18_404f20_lec1.pdf"],
  },
  {
    id: "pushdown-automaton", label: "Pushdown Automaton", aliases: ["PDA"], added: "2026-09-07T10:00:00Z",
    definition: "A pushdown automaton combines finite control with a stack whose top can be inspected and changed by transitions.",
    motionThesis: "Typed opening brackets push three stack symbols, and matching closing brackets pop them in reverse order before acceptance at end of input.",
    distinction: "Typed last-in-first-out memory changes while the processing control state stays fixed.",
    facets: ["algorithms", "formal languages", "stack memory"], cycleSeconds: 9,
    references: ["https://ocw.mit.edu/courses/18-404j-theory-of-computation-fall-2020/a22fce6f6824c53dbb79a0da786966a6_MIT18_404f20_lec4.pdf"],
  },
  {
    id: "kmp-string-search", label: "KMP String Search", aliases: ["Knuth–Morris–Pratt", "prefix-function search"], added: "2026-09-07T10:00:00Z",
    definition: "KMP uses a pattern's prefix structure to continue matching after a mismatch without moving the text position backward.",
    motionThesis: "A mismatch holds the text cursor fixed while the pattern shifts two positions and retains its already matched ABA prefix.",
    distinction: "Failure-link reuse of matched symbols, rather than naive retries or a generic automaton diagram.",
    facets: ["algorithms", "strings", "pattern matching"], cycleSeconds: 10,
    references: ["https://algs4.cs.princeton.edu/53substring/"],
  },
  {
    id: "bloom-filter", label: "Bloom Filter", aliases: ["probabilistic membership filter"], added: "2026-09-07T10:00:00Z",
    definition: "A Bloom filter sets several hashed bits per insertion; a missing query bit proves absence while all matching bits indicate possible membership.",
    motionThesis: "Two keys populate shared bits, then an uninserted key gets a possible-membership result while another query hits a zero bit and is excluded.",
    distinction: "An explicit false positive and definite negative distinguish probabilistic membership from exact hash-table storage.",
    facets: ["algorithms", "data structures", "probabilistic methods"], cycleSeconds: 10,
    references: ["https://www.cs.princeton.edu/courses/archive/spr05/cos598E/bib/p422-bloom.pdf"],
  },
  {
    id: "quadtree-subdivision", label: "Quadtree Subdivision", aliases: ["point-region quadtree", "spatial subdivision"], added: "2026-09-07T10:00:00Z",
    definition: "A planar quadtree recursively divides regions into four child quadrants to organize spatial data.",
    motionThesis: "The third point splits a capacity-two root, then a crowded child alone subdivides at its midpoint while empty quadrants remain.",
    distinction: "Adaptive four-way spatial subdivision rather than decision-tree binary tests or global clustering.",
    facets: ["algorithms", "data structures", "spatial indexing"], cycleSeconds: 9,
    references: ["https://xlinux.nist.gov/dads/HTML/quadtree.html"],
  },
  {
    id: "convex-hull", label: "Convex Hull", aliases: ["planar convex hull", "Graham scan"], added: "2026-09-07T10:00:00Z",
    definition: "The convex hull is the smallest convex set containing a collection of points.",
    motionThesis: "An angular scan grows a candidate boundary, removes the interior vertex that creates a non-convex turn, and closes the hull.",
    distinction: "Geometric orientation tests remove a concavity rather than selecting weighted graph edges.",
    facets: ["algorithms", "computational geometry", "orientation"], cycleSeconds: 9,
    references: ["https://algs4.cs.princeton.edu/99hull/GrahamScan.java.html"],
  },
]);
