import { expansionEntries } from "./expansion-entry.js";

export const CONCEPTS = expansionEntries("mathematics", "statistics-probability", [
  {
    id: "histogram-binning", label: "Histogram Binning",
    definition: "A histogram counts observations within adjacent numeric intervals.",
    motionThesis: "Value markers drop into their matching intervals and build bars one observation at a time.",
    distinction: "Bin assignment and accumulation, without the Galton Board's bouncing pegs.",
    facets: ["statistics", "distributions"], cycleSeconds: 8,
    references: ["https://www.itl.nist.gov/div898/handbook/eda/section3/histogra.htm"],
  },
  {
    id: "empirical-cdf", label: "Empirical Cumulative Distribution", aliases: ["ECDF"],
    definition: "The empirical cumulative distribution gives the fraction of observations at or below each value.",
    motionThesis: "A threshold crosses sorted samples while a linked staircase rises by one equal increment per observation.",
    distinction: "A cumulative threshold and staircase rather than disjoint bin heights.",
    facets: ["statistics", "ranks"], cycleSeconds: 7,
    references: ["https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ecdf.html"],
  },
  {
    id: "box-plot-quartiles", label: "Box Plot Quartiles",
    definition: "A box plot summarizes ordered observations using the median, quartiles, whiskers, and possible outliers.",
    motionThesis: "Ordered observations project onto quartile gates, a median, and whiskers spanning the non-outlying extremes.",
    distinction: "Rank-to-summary geometry; this symmetric example has no Tukey outliers.",
    facets: ["statistics", "quantiles"], cycleSeconds: 8,
    references: ["https://www.itl.nist.gov/div898/handbook/eda/section3/boxplot.htm"],
  },
  {
    id: "bootstrap-resampling", label: "Bootstrap Resampling",
    definition: "Bootstrapping estimates sampling variability by repeatedly sampling observed data with replacement.",
    motionThesis: "Copies of source observations fill resample rows, including repeated selections, before each row yields a mean.",
    distinction: "Source observations remain available after copying, unlike new population sampling or held-out folds.",
    facets: ["statistics", "sampling", "uncertainty"], cycleSeconds: 9,
    references: ["https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.bootstrap.html"],
  },
  {
    id: "confidence-interval-coverage", label: "Confidence Interval Coverage",
    definition: "A confidence procedure produces intervals that cover a fixed parameter at a specified long-run rate.",
    motionThesis: "Repeated sample intervals appear across a fixed truth line, with both covering and missing intervals retained.",
    distinction: "The parameter stays fixed; the small illustrative sample does not claim an exact coverage percentage.",
    facets: ["statistics", "inference", "uncertainty"], cycleSeconds: 9,
    references: ["https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.bootstrap.html"],
  },
  {
    id: "central-limit-theorem", label: "Central Limit Theorem", aliases: ["CLT"],
    definition: "Under suitable conditions, standardized averages of independent samples approach a normal distribution.",
    motionThesis: "Samples from a skewed distribution collapse to means that accumulate into a more symmetric distribution below.",
    distinction: "Shows averaging explicitly, rather than reusing the Galton Board or a thermal distribution.",
    facets: ["statistics", "sampling", "averages"], cycleSeconds: 10,
    references: ["https://ocw.mit.edu/courses/18-05-introduction-to-probability-and-statistics-spring-2022/mit18_05_s22_probability.pdf"],
  },
  {
    id: "law-of-large-numbers", label: "Law of Large Numbers", aliases: ["LLN"],
    definition: "For independent identically distributed observations with a finite mean, sample averages converge toward that mean.",
    motionThesis: "Several irregular running averages extend toward a common expectation while retaining late fluctuations.",
    distinction: "Convergence of running estimates rather than the shape of a distribution of averages.",
    facets: ["statistics", "probability", "convergence"], cycleSeconds: 8,
    references: ["https://ocw.mit.edu/courses/18-05-introduction-to-probability-and-statistics-spring-2022/mit18_05_s22_probability.pdf"],
  },
  {
    id: "bayesian-updating", label: "Bayesian Updating", aliases: ["Bayes theorem", "posterior probability"],
    definition: "Bayesian inference combines prior probabilities with the likelihood of evidence to obtain posterior probabilities.",
    motionThesis: "Evidence retains unequal fractions of two prior groups, then the surviving areas expand into a normalized posterior.",
    distinction: "Area conditioning and renormalization, rather than a generic narrowing bell curve.",
    facets: ["statistics", "inference", "conditional probability"], cycleSeconds: 8,
    references: ["https://ocw.mit.edu/courses/18-05-introduction-to-probability-and-statistics-spring-2022/mit18_05_s22_probability.pdf"],
  },
  {
    id: "poisson-arrival-process", label: "Poisson Arrival Process",
    definition: "A homogeneous Poisson process models independent arrivals with a constant average rate.",
    motionThesis: "Irregularly spaced arrivals cross successive equal time windows and produce different event counts.",
    distinction: "A fixed realization of random event timing rather than periodic pulses.",
    facets: ["probability", "events", "stochastic processes"], cycleSeconds: 9,
    references: ["https://ocw.mit.edu/courses/6-041sc-probabilistic-systems-analysis-and-applied-probability-fall-2013/pages/unit-iii/"],
  },
  {
    id: "markov-chain", label: "Markov Chain",
    definition: "A Markov chain changes state with probabilities determined by its current state.",
    motionThesis: "Each state's probability bar retains half its mass and transfers half to its cyclic successor, conserving total probability.",
    distinction: "Visible splitting and recombination of probability, rather than decorative traffic on a graph.",
    facets: ["probability", "transition matrix", "stochastic processes"], cycleSeconds: 8,
    references: ["https://ocw.mit.edu/courses/6-041sc-probabilistic-systems-analysis-and-applied-probability-fall-2013/pages/unit-iii/"],
  },
  {
    id: "absorbing-random-walk", label: "Absorbing Random Walk",
    definition: "An absorbing random walk stops on reaching an absorbing state such as a boundary.",
    motionThesis: "Walkers take discrete left or right steps along separate tracks and remain fixed after reaching either end barrier.",
    distinction: "Explicit discrete steps and permanent boundary capture distinguish it from Brownian Motion.",
    facets: ["probability", "first passage", "stochastic processes"], cycleSeconds: 10,
    references: ["https://ocw.mit.edu/courses/6-041sc-probabilistic-systems-analysis-and-applied-probability-fall-2013/pages/unit-iii/"],
  },
  {
    id: "monte-carlo-area", label: "Monte Carlo Area Estimation",
    definition: "Monte Carlo integration can estimate an area's fraction of a bounding region from randomly sampled point membership.",
    motionThesis: "Uniform sample locations reveal inside or outside membership, and a matching tally forms the sampled area fraction.",
    distinction: "Geometric membership contributes to an explicit fraction; points are not decorative particles.",
    facets: ["probability", "integration", "sampling"], cycleSeconds: 8,
    references: ["https://www.stat.cmu.edu/~cshalizi/statcomp/14/lectures/25/lecture-25.html"],
  },
  {
    id: "rejection-sampling", label: "Rejection Sampling",
    definition: "Rejection sampling accepts proposals according to a target density bounded by a proposal envelope.",
    motionThesis: "Candidates under a horizontal envelope either fall to the sample strip when beneath the target curve or remain crossed out above it.",
    distinction: "Accepted horizontal positions become samples, unlike counting a geometric area fraction.",
    facets: ["probability", "sampling", "Monte Carlo"], cycleSeconds: 8,
    references: ["https://www.cs.cmu.edu/~epxing/Class/10708-19/notes/lecture-13/"],
  },
  {
    id: "metropolis-sampling", label: "Metropolis Sampling",
    definition: "The Metropolis algorithm forms a sampling chain by accepting or rejecting proposals using a target-density ratio.",
    motionThesis: "A current sample proposes neighboring positions; accepted moves advance the chain, while a rejected move retains and records the old position.",
    distinction: "Rejection repeats the current state rather than discarding an independent candidate.",
    facets: ["probability", "MCMC", "sampling"], cycleSeconds: 9,
    references: ["https://www.cs.cmu.edu/~epxing/Class/10708-19/notes/lecture-14/"],
  },
  {
    id: "kernel-density-estimation", label: "Kernel Density Estimation", aliases: ["KDE"],
    definition: "Kernel density estimation sums smooth kernels centered on observed samples to estimate a probability density.",
    motionThesis: "Individual sample-centered kernels contribute successively to a correctly summed density curve.",
    distinction: "Kernel superposition, rather than histogram bins or a distribution of sample averages.",
    facets: ["statistics", "density", "smoothing"], cycleSeconds: 8,
    references: ["https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gaussian_kde.html"],
  },
  {
    id: "autocorrelation", label: "Autocorrelation",
    definition: "Autocorrelation measures association between a time series and lagged copies of itself.",
    motionThesis: "A shifted copy of a finite signed sequence aligns and opposes its original, while each lag's normalized correlation is recorded below.",
    distinction: "Lagged comparison with signed products rather than generic wave interference.",
    facets: ["statistics", "time series", "signal processing"], cycleSeconds: 8,
    references: ["https://www.itl.nist.gov/div898/handbook/eda/section3/eda35c.htm"],
  },
]);
