// Gallery manifest — single source of truth for the Physics & Movement gallery.
// This pure-data module drives physics/gallery/index.js.
// The order of CONCEPTS is the display order in the gallery.

export const CATEGORIES = [
  { id: "mechanics", title: "Classical Mechanics & Kinematics" },
  { id: "orbital", title: "Orbital Mechanics & Gravitation" },
  { id: "waves", title: "Waves, Oscillations & Optics" },
  { id: "fluids", title: "Fluid Dynamics & Thermodynamics" },
  { id: "fields", title: "Fields, Electromagnetism & Linkages" },
];

export const CONCEPTS = [
  // --- Category: Classical Mechanics & Kinematics ---
  {
    tag: "physics-projectile-arc",
    label: "Projectile Arc",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:00:00Z",
    updated: "2026-08-14T05:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-spring-mass-damper",
    label: "Spring-Mass Damper",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:00:00Z",
    updated: "2026-08-14T05:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-double-pendulum",
    label: "Double Pendulum",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:00:00Z",
    updated: "2026-08-14T05:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-centripetal-force",
    label: "Centripetal Force",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:00:00Z",
    updated: "2026-08-14T05:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-incline-friction",
    label: "Incline & Friction",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:00:00Z",
    updated: "2026-08-14T05:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-collision-elastic",
    label: "Elastic Collision",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:00:00Z",
    updated: "2026-08-14T05:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },

  // --- Category: Orbital Mechanics & Gravitation ---
  {
    tag: "physics-kepler-orbit",
    label: "Kepler Orbit",
    category: "orbital",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:10:00Z",
    updated: "2026-08-14T05:10:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-lagrange-points",
    label: "Lagrange Points",
    category: "orbital",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:10:00Z",
    updated: "2026-08-14T05:10:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-gravitational-slingshot",
    label: "Gravity Assist Slingshot",
    category: "orbital",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:10:00Z",
    updated: "2026-08-14T05:10:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-three-body-figure8",
    label: "Three-Body Figure 8",
    category: "orbital",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:10:00Z",
    updated: "2026-08-14T05:10:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-black-hole-lensing",
    label: "Black Hole Lensing",
    category: "orbital",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:10:00Z",
    updated: "2026-08-14T05:10:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-tidal-locking",
    label: "Tidal Locking",
    category: "orbital",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:10:00Z",
    updated: "2026-08-14T05:10:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },

  // --- Category: Waves, Oscillations & Optics ---
  {
    tag: "physics-wave-interference",
    label: "Wave Interference",
    category: "waves",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:20:00Z",
    updated: "2026-08-14T05:20:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-standing-wave",
    label: "Standing Wave Resonance",
    category: "waves",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:20:00Z",
    updated: "2026-08-14T05:20:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-doppler-effect",
    label: "Doppler Shift",
    category: "waves",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:20:00Z",
    updated: "2026-08-14T05:20:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-snells-law-refraction",
    label: "Snell's Law Refraction",
    category: "waves",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:20:00Z",
    updated: "2026-08-14T05:20:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-foucault-pendulum",
    label: "Foucault Pendulum",
    category: "waves",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:20:00Z",
    updated: "2026-08-14T05:20:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-chladni-plate",
    label: "Chladni Resonance Plate",
    category: "waves",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:20:00Z",
    updated: "2026-08-14T05:20:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
];
