// Gallery manifest — single source of truth for the Physics & Movement gallery.
// This pure-data module drives physics/gallery/index.js.
// The order of CONCEPTS is the display order in the gallery.

export const CATEGORIES = [
  { id: "mechanics", title: "Classical Mechanics & Kinematics" },
  { id: "orbital", title: "Orbital Mechanics & Gravitation" },
  { id: "waves", title: "Waves, Oscillations & Optics" },
  { id: "fluids", title: "Fluid Dynamics & Thermodynamics" },
  { id: "fields", title: "Fields, Electromagnetism & Linkages" },
];

export const CONCEPTS = [
  // --- Category: Classical Mechanics & Kinematics ---
  {
    tag: "physics-projectile-arc",
    label: "Projectile Arc",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:00:00Z",
    updated: "2026-08-14T05:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-spring-mass-damper",
    label: "Spring-Mass Damper",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:00:00Z",
    updated: "2026-08-14T05:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-double-pendulum",
    label: "Double Pendulum",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:00:00Z",
    updated: "2026-08-14T05:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-centripetal-force",
    label: "Centripetal Force",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:00:00Z",
    updated: "2026-08-14T05:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-incline-friction",
    label: "Incline & Friction",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:00:00Z",
    updated: "2026-08-14T05:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-collision-elastic",
    label: "Elastic Collision",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:00:00Z",
    updated: "2026-08-14T05:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
];
