// Gallery manifest — single source of truth for the Physics & Movement gallery.
// This pure-data module drives physics/gallery/index.js.
// The order of CONCEPTS is the display order in the gallery.

export const CATEGORIES = [
  { id: "mechanics", title: "Classical Mechanics & Kinematics" },
  { id: "orbital", title: "Orbital Mechanics & Gravitation" },
  { id: "waves", title: "Waves, Oscillations & Optics" },
  { id: "fluids", title: "Fluid Dynamics & Thermodynamics" },
  { id: "fields", title: "Fields, Electromagnetism & Linkages" },
  { id: "relativity", title: "Relativity & Spacetime" },
  { id: "quantum", title: "Quantum Mechanics & Modern Physics" },
];

export const CONCEPTS = [
  // --- Category: Classical Mechanics & Kinematics ---
  {
    tag: "physics-projectile-arc",
    label: "Projectile Arc",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:00:00Z",
    updated: "2026-08-14T05:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-spring-mass-damper",
    label: "Spring-Mass Damper",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:00:00Z",
    updated: "2026-08-14T05:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-double-pendulum",
    label: "Double Pendulum",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:00:00Z",
    updated: "2026-08-14T05:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-centripetal-force",
    label: "Centripetal Force",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:00:00Z",
    updated: "2026-08-14T05:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-incline-friction",
    label: "Incline & Friction",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:00:00Z",
    updated: "2026-08-14T05:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-collision-elastic",
    label: "Elastic Collision",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:00:00Z",
    updated: "2026-08-14T05:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-atwood-machine",
    label: "Atwood Machine",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T02:55:00Z",
    updated: "2026-08-15T02:55:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-brachistochrone-curve",
    label: "Brachistochrone Curve",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T02:55:00Z",
    updated: "2026-08-15T02:55:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-gyroscopic-precession",
    label: "Gyroscopic Precession",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T02:55:00Z",
    updated: "2026-08-15T02:55:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-coriolis-deflection",
    label: "Coriolis Deflection",
    category: "mechanics",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T02:55:00Z",
    updated: "2026-08-15T02:55:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },

  // --- Category: Orbital Mechanics & Gravitation ---
  {
    tag: "physics-kepler-orbit",
    label: "Kepler Orbit",
    category: "orbital",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:10:00Z",
    updated: "2026-08-14T05:10:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-lagrange-points",
    label: "Lagrange Points",
    category: "orbital",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:10:00Z",
    updated: "2026-08-14T05:10:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-gravitational-slingshot",
    label: "Gravity Assist Slingshot",
    category: "orbital",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:10:00Z",
    updated: "2026-08-14T05:10:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-three-body-figure8",
    label: "Three-Body Figure 8",
    category: "orbital",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:10:00Z",
    updated: "2026-08-14T05:10:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-black-hole-lensing",
    label: "Black Hole Lensing",
    category: "orbital",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:10:00Z",
    updated: "2026-08-14T05:10:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-tidal-locking",
    label: "Tidal Locking",
    category: "orbital",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:10:00Z",
    updated: "2026-08-14T05:10:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-hohmann-transfer",
    label: "Hohmann Transfer",
    category: "orbital",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T02:58:00Z",
    updated: "2026-08-15T02:58:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-roche-limit",
    label: "Roche Limit Disruption",
    category: "orbital",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T02:58:00Z",
    updated: "2026-08-15T02:58:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-gravitational-redshift",
    label: "Gravitational Redshift",
    category: "orbital",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T02:58:00Z",
    updated: "2026-08-15T02:58:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-orbital-resonance",
    label: "Laplace Resonance (1:2:4)",
    category: "orbital",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T02:58:00Z",
    updated: "2026-08-15T02:58:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },

  // --- Category: Waves, Oscillations & Optics ---
  {
    tag: "physics-wave-interference",
    label: "Wave Interference",
    category: "waves",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:20:00Z",
    updated: "2026-08-14T05:20:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-standing-wave",
    label: "Standing Wave Resonance",
    category: "waves",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:20:00Z",
    updated: "2026-08-14T05:20:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-doppler-effect",
    label: "Doppler Shift",
    category: "waves",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:20:00Z",
    updated: "2026-08-14T05:20:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-snells-law-refraction",
    label: "Snell's Law Refraction",
    category: "waves",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:20:00Z",
    updated: "2026-08-14T05:20:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-foucault-pendulum",
    label: "Foucault Pendulum",
    category: "waves",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:20:00Z",
    updated: "2026-08-14T05:20:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-chladni-plate",
    label: "Chladni Resonance Plate",
    category: "waves",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:20:00Z",
    updated: "2026-08-14T05:20:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-mach-cone",
    label: "Mach Cone & Shockwave",
    category: "waves",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:00:00Z",
    updated: "2026-08-15T03:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-total-internal-reflection",
    label: "Total Internal Reflection",
    category: "waves",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:00:00Z",
    updated: "2026-08-15T03:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-michelson-interferometer",
    label: "Michelson Interferometer",
    category: "waves",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:00:00Z",
    updated: "2026-08-15T03:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-fabry-perot-cavity",
    label: "Fabry-Pérot Optical Cavity",
    category: "waves",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:00:00Z",
    updated: "2026-08-15T03:00:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },

  // --- Category: Fluid Dynamics & Thermodynamics ---
  {
    tag: "physics-vortex-shedding",
    label: "Vortex Shedding (Kármán)",
    category: "fluids",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:30:00Z",
    updated: "2026-08-14T05:30:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-brownian-motion",
    label: "Brownian Motion",
    category: "fluids",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:30:00Z",
    updated: "2026-08-14T05:30:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-capillary-action",
    label: "Capillary Meniscus Action",
    category: "fluids",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:30:00Z",
    updated: "2026-08-14T05:30:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-buoyancy-archimedes",
    label: "Archimedes Buoyancy",
    category: "fluids",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:30:00Z",
    updated: "2026-08-14T05:30:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-bernoulli-venturi",
    label: "Bernoulli Venturi Tube",
    category: "fluids",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:30:00Z",
    updated: "2026-08-14T05:30:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-convection-currents",
    label: "Rayleigh-Bénard Convection",
    category: "fluids",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:30:00Z",
    updated: "2026-08-14T05:30:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-hydraulic-jump",
    label: "Hydraulic Jump",
    category: "fluids",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:05:00Z",
    updated: "2026-08-15T03:05:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-magnus-effect",
    label: "Magnus Effect Lift",
    category: "fluids",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:05:00Z",
    updated: "2026-08-15T03:05:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-rayleigh-taylor",
    label: "Rayleigh-Taylor Instability",
    category: "fluids",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:05:00Z",
    updated: "2026-08-15T03:05:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-carnot-cycle",
    label: "Carnot Heat Engine",
    category: "fluids",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:05:00Z",
    updated: "2026-08-15T03:05:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },

  // --- Category: Fields, Electromagnetism & Linkages ---
  {
    tag: "physics-lorentz-force",
    label: "Lorentz Force",
    category: "fields",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:40:00Z",
    updated: "2026-08-14T05:40:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-four-bar-linkage",
    label: "Four-Bar Linkage",
    category: "fields",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:40:00Z",
    updated: "2026-08-14T05:40:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-solenoid-inductance",
    label: "Solenoid Inductance",
    category: "fields",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:40:00Z",
    updated: "2026-08-14T05:40:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-cycloid-gear",
    label: "Epicyclic Planetary Gear",
    category: "fields",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:40:00Z",
    updated: "2026-08-14T05:40:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-particle-accelerator",
    label: "Synchrotron Accelerator",
    category: "fields",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:40:00Z",
    updated: "2026-08-14T05:40:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-superconductor-levitation",
    label: "Meissner Levitation",
    category: "fields",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-14T05:40:00Z",
    updated: "2026-08-14T05:40:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-homopolar-generator",
    label: "Faraday Homopolar Disk",
    category: "fields",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:10:00Z",
    updated: "2026-08-15T03:10:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-hall-effect",
    label: "Hall Effect Voltage",
    category: "fields",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:10:00Z",
    updated: "2026-08-15T03:10:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-helmholtz-coils",
    label: "Helmholtz Coils",
    category: "fields",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:10:00Z",
    updated: "2026-08-15T03:10:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-magnetic-mirror",
    label: "Magnetic Mirror Bottle",
    category: "fields",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:10:00Z",
    updated: "2026-08-15T03:10:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },

  // --- Category: Relativity & Spacetime ---
  {
    tag: "physics-light-cone",
    label: "Spacetime Light Cone",
    category: "relativity",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:20:00Z",
    updated: "2026-08-15T03:20:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-lorentz-contraction",
    label: "Lorentz Length Contraction",
    category: "relativity",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:20:00Z",
    updated: "2026-08-15T03:20:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-time-dilation",
    label: "Relativistic Time Dilation",
    category: "relativity",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:20:00Z",
    updated: "2026-08-15T03:20:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-gravitational-waves",
    label: "Gravitational Wave Quadrupole Strain",
    category: "relativity",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:20:00Z",
    updated: "2026-08-15T03:20:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-frame-dragging",
    label: "Lense-Thirring Frame Dragging",
    category: "relativity",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:20:00Z",
    updated: "2026-08-15T03:20:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-schwarzschild-geodesic",
    label: "Schwarzschild Perihelion Precession",
    category: "relativity",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:20:00Z",
    updated: "2026-08-15T03:20:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-minkowski-diagram",
    label: "Minkowski Spacetime Diagram",
    category: "relativity",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:20:00Z",
    updated: "2026-08-15T03:20:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-gravitational-time-dilation",
    label: "Gravitational Time Dilation",
    category: "relativity",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:20:00Z",
    updated: "2026-08-15T03:20:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },

  // --- Category: Quantum Mechanics & Modern Physics ---
  {
    tag: "physics-quantum-tunneling",
    label: "Quantum Barrier Tunneling",
    category: "quantum",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:30:00Z",
    updated: "2026-08-15T03:30:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-stern-gerlach",
    label: "Stern-Gerlach Spin Splitting",
    category: "quantum",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:30:00Z",
    updated: "2026-08-15T03:30:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-photoelectric-effect",
    label: "Photoelectric Effect",
    category: "quantum",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:30:00Z",
    updated: "2026-08-15T03:30:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-quantum-harmonic-oscillator",
    label: "Quantum Harmonic Oscillator",
    category: "quantum",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:30:00Z",
    updated: "2026-08-15T03:30:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-bohr-atom",
    label: "Bohr Atom Transitions",
    category: "quantum",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:30:00Z",
    updated: "2026-08-15T03:30:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-compton-scattering",
    label: "Compton X-Ray Scattering",
    category: "quantum",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:30:00Z",
    updated: "2026-08-15T03:30:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-zeeman-effect",
    label: "Zeeman Spectral Splitting",
    category: "quantum",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:30:00Z",
    updated: "2026-08-15T03:30:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
  {
    tag: "physics-electron-double-slit",
    label: "Electron Wave Interference",
    category: "quantum",
    origin: { contributions: [{ agent: "gemini", model: null, version: null }] },
    added: "2026-08-15T03:30:00Z",
    updated: "2026-08-15T03:30:00Z",
    versioned: false,
    badge: "New v1",
    badgeCls: "meta-status-new",
    default: null,
    versions: [],
  },
];

