/* =========================================
   PHOSPHOR THEME SHIM
   Generated by StarlightDaemon Project

   Tiny vanilla-JS helper shared by the demo pages.
   Applies the persisted (or ?phosphor= query) theme by
   setting data-phosphor on <html> and lets the CSS
   variable cascade do the rest. No framework, no build.

   Exposes window.AfterglowsPhosphor = {
     THEMES, get(), set(key), onChange(fn)
   }
   ========================================= */
(function () {
    'use strict';

    var THEMES = [
        { key: 'p1',   name: 'Green',      note: 'P1 — classic green screen', phosphor: true },
        { key: 'p31',  name: 'Fast Green', note: 'P31 — Amdek / DEC / Tektronix', phosphor: true },
        { key: 'p3',   name: 'Amber',      note: 'P3 — DEC VT220 / Hercules', phosphor: true },
        { key: 'p4',   name: 'Paper White', note: 'P4 — TRS-80 / Commodore PET', phosphor: true },
        { key: 'p7',   name: 'Blue-White', note: 'P7 — radar / oscilloscope cascade', phosphor: true },
        { key: 'p2',   name: 'Stoplight',  note: 'P2 — long-persistence oscillography', phosphor: true },
        { key: 'p14',  name: 'Violet',     note: 'P14 — rare blue-violet', phosphor: true },
        { key: 'neon', name: 'Neon Blue',  note: 'modern cyberpunk — not a phosphor', phosphor: false }
    ];

    var STORAGE_KEY = 'afterglows-phosphor';
    var root = document.documentElement;
    var listeners = [];

    function isValid(key) {
        return THEMES.some(function (t) { return t.key === key; });
    }

    function current() {
        return root.getAttribute('data-phosphor') || 'p1';
    }

    function apply(key, persist) {
        if (!isValid(key)) { return; }
        if (key === 'p1') {
            root.removeAttribute('data-phosphor');
        } else {
            root.setAttribute('data-phosphor', key);
        }
        if (persist) {
            try { localStorage.setItem(STORAGE_KEY, key); } catch (e) { /* private mode */ }
        }
        listeners.forEach(function (fn) { fn(key); });
    }

    // Boot order: explicit ?phosphor= query wins (preview / deep link,
    // not persisted), else the persisted choice.
    var fromQuery = new URLSearchParams(window.location.search).get('phosphor');
    if (fromQuery && isValid(fromQuery)) {
        apply(fromQuery, false);
    } else {
        var stored = null;
        try { stored = localStorage.getItem(STORAGE_KEY); } catch (e) { /* ignore */ }
        if (stored && isValid(stored)) { apply(stored, false); }
    }

    // Follow changes made in another same-origin page (e.g. the demo hub).
    window.addEventListener('storage', function (e) {
        if (e.key === STORAGE_KEY && e.newValue && isValid(e.newValue)) {
            apply(e.newValue, false);
        }
    });

    window.AfterglowsPhosphor = {
        THEMES: THEMES,
        get: current,
        set: function (key) { apply(key, true); },
        onChange: function (fn) { listeners.push(fn); }
    };
}());
